### ISSUE TITLE
OSError: [WinError 126]      Error code: 1

### ISSUE THREAD

**Issue by gee420365** [aitrepreneur/REGULARIZATION-IMAGES-SD#1]
This happens after installing Dream booth add-on.

venv "C:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Commit hash: ac085628540d0ec6a988fad93f5b8f2154209571
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\launch.py", line 251, in <module>
    prepare_enviroment()
  File "C:\AI\stable-diffusion-webui\launch.py", line 172, in prepare_enviroment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "C:\AI\stable-diffusion-webui\launch.py", line 58, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "C:\AI\stable-diffusion-webui\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "C:\AI\stable-diffusion-webui\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\__init__.py", line 140, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.

**Comment by sebaxakerhtc** [comment]
> Torch is not able to use GPU

Looks like you don't have a supported GPU
